//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADMIN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRol
    {
        public int idRol { get; set; }
        public string vNameEn { get; set; }
        public string vNameEs { get; set; }
        public Nullable<System.DateTime> dCreateDate { get; set; }
        public Nullable<System.DateTime> dUpdateDate { get; set; }
        public string vCreateUser { get; set; }
        public string vUpdateUser { get; set; }
        public Nullable<bool> bActive { get; set; }
    }
}
