//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADMIN.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblUser
    {
        public int idUser { get; set; }
        [Display(Name = "Nombre Usuario")]
        [Required(ErrorMessage = "Campo Vacio")]
        [StringLength(30,MinimumLength = 4)]
        public string UserName { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        [Display(Name = "Contraseña")]
        [Required(ErrorMessage = "Campo Vacio")]
        [StringLength(30,MinimumLength = 4)]
        public string Password { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string CreateUser { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
